runtime: nodejs14

env_variables:
  # Firebase Configuration
  FIREBASE_API_KEY: AIzaSyCq6oYSEYgv06BLONDYujOaIskHVfeuXVc
  FIREBASE_AUTH_DOMAIN: library-management-system-lms.firebaseapp.com
  FIREBASE_PROJECT_ID: library-management-system-lms
  FIREBASE_STORAGE_BUCKET: library-management-system-lms.appspot.com
  FIREBASE_MESSAGING_SENDER_ID: 1086641789904
  FIREBASE_APP_ID: 1:1086641789904:web:798b35829f4eba8e8637d5
  FIREBASE_MEASUREMENT_ID: G-TXLJ7LCT3X

handlers:
  - url: /(.*\.(gif|png|jpg|ico|txt|js|css|html|json|svg|woff|woff2|ttf|eot|map))$
    static_files: dist/lms-portal-v1/\1
    upload: dist/lms-portal-v1/.*\.(gif|png|jpg|jpeg|ico|txt|js|css|html|json|svg|woff|woff2|ttf|eot|map)$
    expiration: "7d"

  - url: /.*
    static_files: dist/lms-portal-v1/index.html
    upload: dist/lms-portal-v1/index.html
    secure: always
